# Generated by Django 5.1.3 on 2025-12-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_language',
            field=models.CharField(default='Bangla', help_text='Bangla / English / Mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='communication_tone',
            field=models.CharField(default='Friendly', help_text='Friendly / Professional / Aggressive', max_length=50),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='product_category',
            field=models.CharField(default='General', help_text='E.g., Fashion, Electronics, Food', max_length=100),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='target_customer',
            field=models.CharField(default='Everyone', help_text='E.g., Men 20-30, Housewives, Students', max_length=200),
        ),
    ]
