# Generated by Django 5.1.3 on 2026-01-01 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price_1m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_3m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_6m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_12m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price_1m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price_3m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price_6m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price_12m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('team_members_limit', models.IntegerField(default=1)),
                ('warehouses_limit', models.IntegerField(default=1)),
                ('monthly_invoices_limit', models.IntegerField(default=500)),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months')])),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
